[pytest]

addopts = -s -v
    # автоматически добавляет флаги при запуске, --alluredir=./allure-results

python_files = test_*.py *_test.py
    # устанавливаем правила, по дефолту, просто указываем, воспринимаются как тестовые
    # указываем явно, тестировщикам говорим, что у нас тестовые файлы такие)
python_classes = Test*
    # по дефолту
python_functions = test_*
    # по дефолту

markers=
    users: Маркировка для тестов, связанных с пользователями
    files: Маркировка для тестов, связанных с файлами
    courses: Маркировка для тестов, связанных с курсами
    exercises: Маркировка для тестов, связанных с заданиями
    authentication: Маркировка для тестов, связанных authentication
    regression: Маркировка для регрессионных тестов


